// dnsmasq is Copyright (c) 2000-2024 Simon Kelley
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; version 2 dated June, 1991, or
//  (at your option) version 3 dated 29 June, 2007.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//    
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

//! D-Bus control interface for runtime configuration and monitoring of dnsmasq
//!
//! # Purpose
//!
//! This module implements a D-Bus Inter-Process Communication (IPC) interface that provides
//! runtime control and monitoring capabilities for dnsmasq without requiring daemon restart
//! or SIGHUP signal. The interface exports methods under the `uk.org.thekelleys.dnsmasq`
//! interface name on the system D-Bus bus, enabling dynamic configuration changes and
//! status queries.
//!
//! This is commonly used by NetworkManager, systemd-resolved, and other system management
//! tools to integrate dnsmasq into dynamic network configurations.
//!
//! # Architecture
//!
//! Replaces C's manual libdbus-1 FFI calls with safe Rust zbus crate providing async D-Bus
//! bindings with automatic message serialization/deserialization via the `#[dbus_interface]`
//! macro. Eliminates manual DBusMessage construction, watch management, and introspection
//! XML generation through declarative Rust attributes.
//!
//! # Memory Safety Improvements
//!
//! | C Pattern | Rust Replacement | Safety Benefit |
//! |-----------|------------------|----------------|
//! | Manual libdbus-1 FFI | zbus safe async bindings | No manual message lifecycle management |
//! | DBusMessageIter parsing | Automatic serde deserialization | No buffer overruns in type extraction |
//! | Manual watch registration | zbus async runtime integration | No manual FD polling |
//! | NULL pointer checks | Option<T> and Result<T, E> | Type-safe null handling |
//! | errno error returns | zbus fdo::Error enum | Explicit error propagation |
//!
//! # D-Bus Interface Specification
//!
//! **Interface Name**: `uk.org.thekelleys.dnsmasq`
//! **Object Path**: `/uk/org/thekelleys/dnsmasq`
//!
//! ## Methods
//!
//! - **GetVersion**() → String
//!   - Returns dnsmasq version string
//!
//! - **ClearCache**()
//!   - Flushes DNS cache and reloads configuration
//!
//! - **GetMetrics**() → Dict<String, u32>
//!   - Returns runtime statistics (cache hits/misses, queries forwarded, etc.)
//!
//! - **SetServers**(servers: Array<Struct<String, u32 or [u8; 16]>>)
//!   - Dynamically configure upstream DNS servers
//!   - IPv4: String domain + u32 address
//!   - IPv6: String domain + [u8; 16] address
//!   - Empty domain = global server, non-empty = domain-specific
//!
//! - **SetServersEx**(servers: Array<Struct<String, u32 or [u8; 16], String source>>)
//!   - Extended server configuration with source address binding
//!
//! - **SetDomainServers**(servers: Array<Struct<String, Array<String>>>)
//!   - Configure domain-specific server lists
//!
//! - **AddDhcpLease**(expiry: u64, hwaddr: Array<u8>, ipaddr: u32 or [u8; 16], hostname: String, client_id: Array<u8>)
//!   - Manually add DHCP lease entry
//!   - Updates both lease database and DNS cache
//!
//! - **DeleteDhcpLease**(hwaddr: Array<u8>, ipaddr: u32 or [u8; 16])
//!   - Manually remove DHCP lease entry
//!
//! ## Signals
//!
//! - **DhcpLeaseAdded**(ipaddr: String, hwaddr: String, hostname: String)
//!   - Emitted when new DHCP lease is allocated
//!
//! - **DhcpLeaseDeleted**(ipaddr: String, hwaddr: String, hostname: String)
//!   - Emitted when DHCP lease expires or is released
//!
//! - **DhcpLeaseUpdated**(ipaddr: String, hwaddr: String, hostname: String)
//!   - Emitted when existing DHCP lease is renewed
//!
//! - **Up**()
//!   - Emitted when daemon completes initialization
//!
//! # Integration with Event Loop
//!
//! The D-Bus connection runs in a separate tokio task spawned via `tokio::spawn()`,
//! processing messages asynchronously without blocking the main event loop. Daemon
//! state is accessed via `Arc<RwLock<Daemon>>` for thread-safe concurrent access
//! from D-Bus method handlers.
//!
//! # Configuration Compatibility
//!
//! Maintains 100% backward compatibility with C implementation:
//! - Exact method signatures and argument types (UINT32 for IPv4, BYTE[16] for IPv6)
//! - Same signal names and parameters
//! - Introspection XML automatically generated by zbus matches C version
//! - Error response format (fdo.Error) matches D-Bus specification
//!
//! # RFC Compliance
//!
//! - D-Bus specification for system bus services
//! - org.freedesktop.DBus.Introspectable interface for introspection
//! - Proper D-Bus type system marshalling
//!
//! # Usage Example
//!
//! ```rust,ignore
//! use dnsmasq::integration::dbus::{init_dbus, DbusInterface};
//! use dnsmasq::core::daemon::Daemon;
//! use std::sync::Arc;
//! use tokio::sync::RwLock;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let daemon = Arc::new(RwLock::new(Daemon::new(...)));
//!     
//!     // Initialize D-Bus interface
//!     let dbus_interface = init_dbus(daemon.clone()).await?;
//!     
//!     // Run D-Bus event loop in background task
//!     let dbus_handle = tokio::spawn(async move {
//!         dbus_interface.run().await
//!     });
//!     
//!     // Main event loop continues...
//!     
//!     dbus_handle.await??;
//!     Ok(())
//! }
//! ```
//!
//! # Original C Mapping
//!
//! Refactored from `src/dbus.c` with the following transformations:
//! - `dbus_connection_*` → `zbus::Connection` async methods
//! - `DBusMessage*` → Rust types with serde serialization
//! - Manual message iteration → Automatic parameter binding
//! - Watch callbacks → zbus async runtime integration
//! - Introspection XML → #[dbus_interface] derive macro

use std::collections::HashMap;
use std::fmt;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
use std::sync::Arc;
use std::time::{Duration, SystemTime};

use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::sync::{mpsc, RwLock};
use tracing::{debug, error, info, trace, warn};
use zbus::{dbus_interface, interface, Connection, ConnectionBuilder, SignalContext};

use crate::core::config::VERSION;
use crate::core::daemon::Daemon;
use crate::dns::cache::Cache;
use crate::dns::upstream::ServerFlags;
#[cfg(feature = "dhcp")]
use crate::dhcp::lease::LeaseManager;
use crate::logging::logger::Logger;

// ============================================================================
// Constants
// ============================================================================

/// D-Bus interface name
const DBUS_INTERFACE: &str = "uk.org.thekelleys.dnsmasq";

/// D-Bus object path
const DBUS_PATH: &str = "/uk/org/thekelleys/dnsmasq";

/// D-Bus service name
const DBUS_SERVICE: &str = "uk.org.thekelleys.dnsmasq";

// ============================================================================
// Error Types
// ============================================================================

/// D-Bus integration error type
///
/// Represents all error conditions that can occur during D-Bus operations.
/// Mapped to zbus::fdo::Error for transmission to D-Bus clients.
#[derive(Debug, Error)]
pub enum DbusError {
    /// Failed to connect to system D-Bus
    #[error("D-Bus connection failed: {0}")]
    ConnectionFailed(String),
    
    /// Failed to register D-Bus interface
    #[error("D-Bus registration failed: {0}")]
    RegistrationFailed(String),
    
    /// Method call execution failed
    #[error("D-Bus method call failed: {0}")]
    MethodCallFailed(String),
    
    /// Signal emission failed
    #[error("Signal emission failed: {0}")]
    SignalEmitFailed(String),
    
    /// Connection lost
    #[error("D-Bus connection lost")]
    Disconnected,
}

impl From<zbus::Error> for DbusError {
    fn from(err: zbus::Error) -> Self {
        DbusError::ConnectionFailed(err.to_string())
    }
}

impl From<DbusError> for zbus::fdo::Error {
    fn from(err: DbusError) -> Self {
        match err {
            DbusError::ConnectionFailed(msg) => zbus::fdo::Error::Failed(msg),
            DbusError::RegistrationFailed(msg) => zbus::fdo::Error::Failed(msg),
            DbusError::MethodCallFailed(msg) => zbus::fdo::Error::Failed(msg),
            DbusError::SignalEmitFailed(msg) => zbus::fdo::Error::Failed(msg),
            DbusError::Disconnected => zbus::fdo::Error::Disconnected(String::new()),
        }
    }
}

// ============================================================================
// Server Configuration Types
// ============================================================================

/// Server configuration for SetServers method
///
/// Represents an upstream DNS server specification with domain filtering.
/// Empty domain string indicates a global server, non-empty domain indicates
/// domain-specific routing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Domain for filtering (empty = global server)
    pub domain: String,
    /// IP address (IPv4 or IPv6)
    pub address: IpAddr,
}

/// Extended server configuration for SetServersEx method
///
/// Includes source address binding for multi-homed systems.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfigEx {
    /// Domain for filtering (empty = global server)
    pub domain: String,
    /// IP address (IPv4 or IPv6)
    pub address: IpAddr,
    /// Source address for binding (optional)
    pub source: Option<IpAddr>,
}

// ============================================================================
// D-Bus Interface Implementation
// ============================================================================

/// Main D-Bus control interface for dnsmasq
///
/// Implements the uk.org.thekelleys.dnsmasq D-Bus interface using zbus.
/// Holds a reference to the daemon state for accessing cache, servers,
/// and DHCP leases. All methods are async and non-blocking.
pub struct DbusInterface {
    /// Shared daemon state with thread-safe concurrent access
    daemon: Arc<RwLock<Daemon>>,
    
    /// Logger for D-Bus operations
    logger: Arc<Logger>,
    
    /// Signal context for emitting D-Bus signals
    signal_ctx: Arc<RwLock<Option<SignalContext<'static>>>>,
}

impl DbusInterface {
    /// Create new D-Bus interface instance
    ///
    /// # Arguments
    ///
    /// * `daemon` - Shared daemon state
    /// * `logger` - Logger instance for D-Bus operations
    ///
    /// # Examples
    ///
    /// ```rust,ignore
    /// let daemon = Arc::new(RwLock::new(Daemon::new(...)));
    /// let logger = Arc::new(Logger::new(...));
    /// let dbus_interface = DbusInterface::new(daemon, logger);
    /// ```
    pub fn new(daemon: Arc<RwLock<Daemon>>, logger: Arc<Logger>) -> Self {
        Self {
            daemon,
            logger,
            signal_ctx: Arc::new(RwLock::new(None)),
        }
    }

    /// Run the D-Bus interface event loop
    ///
    /// Connects to the system bus, registers the interface, and processes
    /// incoming D-Bus messages. This should be run in a separate tokio task.
    ///
    /// # Errors
    ///
    /// Returns `DbusError` if connection fails or if interface registration fails.
    ///
    /// # Examples
    ///
    /// ```rust,ignore
    /// tokio::spawn(async move {
    ///     dbus_interface.run().await.expect("D-Bus interface failed");
    /// });
    /// ```
    pub async fn run(self) -> Result<(), DbusError> {
        info!("Initializing D-Bus interface on system bus");

        // Build connection to system bus
        let connection = ConnectionBuilder::system()
            .map_err(|e| DbusError::ConnectionFailed(format!("Failed to connect to system bus: {e}")))?
            .name(DBUS_SERVICE)
            .map_err(|e| DbusError::RegistrationFailed(format!("Failed to request service name: {e}")))?
            .serve_at(DBUS_PATH, self)
            .map_err(|e| DbusError::RegistrationFailed(format!("Failed to register interface: {e}")))?
            .build()
            .await
            .map_err(|e| DbusError::ConnectionFailed(format!("Failed to build connection: {e}")))?;

        info!("D-Bus interface registered at {DBUS_PATH}");

        // Keep connection alive
        loop {
            // Process D-Bus messages
            tokio::time::sleep(Duration::from_secs(1)).await;
            
            // Check if connection is still alive
            if connection.is_closed() {
                warn!("D-Bus connection closed");
                return Err(DbusError::Disconnected);
            }
        }
    }

    /// Emit DhcpLeaseAdded signal
    ///
    /// Broadcasts notification when a new DHCP lease is allocated.
    ///
    /// # Arguments
    ///
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    pub async fn emit_dhcp_lease_added(
        &self,
        ipaddr: String,
        hwaddr: String,
        hostname: String,
    ) -> Result<(), DbusError> {
        trace!("Emitting DhcpLeaseAdded signal: ip={ipaddr}, mac={hwaddr}, hostname={hostname}");
        
        if let Some(ctx) = self.signal_ctx.read().await.as_ref() {
            DnsmasqInterface::dhcp_lease_added(ctx, &ipaddr, &hwaddr, &hostname)
                .await
                .map_err(|e| DbusError::SignalEmitFailed(e.to_string()))?;
            debug!("DhcpLeaseAdded signal emitted");
        }
        
        Ok(())
    }

    /// Emit DhcpLeaseDeleted signal
    ///
    /// Broadcasts notification when a DHCP lease expires or is released.
    ///
    /// # Arguments
    ///
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    pub async fn emit_dhcp_lease_deleted(
        &self,
        ipaddr: String,
        hwaddr: String,
        hostname: String,
    ) -> Result<(), DbusError> {
        trace!("Emitting DhcpLeaseDeleted signal: ip={ipaddr}, mac={hwaddr}, hostname={hostname}");
        
        if let Some(ctx) = self.signal_ctx.read().await.as_ref() {
            DnsmasqInterface::dhcp_lease_deleted(ctx, &ipaddr, &hwaddr, &hostname)
                .await
                .map_err(|e| DbusError::SignalEmitFailed(e.to_string()))?;
            debug!("DhcpLeaseDeleted signal emitted");
        }
        
        Ok(())
    }

    /// Emit DhcpLeaseUpdated signal
    ///
    /// Broadcasts notification when an existing DHCP lease is renewed.
    ///
    /// # Arguments
    ///
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    pub async fn emit_dhcp_lease_updated(
        &self,
        ipaddr: String,
        hwaddr: String,
        hostname: String,
    ) -> Result<(), DbusError> {
        trace!("Emitting DhcpLeaseUpdated signal: ip={ipaddr}, mac={hwaddr}, hostname={hostname}");
        
        if let Some(ctx) = self.signal_ctx.read().await.as_ref() {
            DnsmasqInterface::dhcp_lease_updated(ctx, &ipaddr, &hwaddr, &hostname)
                .await
                .map_err(|e| DbusError::SignalEmitFailed(e.to_string()))?;
            debug!("DhcpLeaseUpdated signal emitted");
        }
        
        Ok(())
    }

    /// Emit Up signal
    ///
    /// Broadcasts notification when daemon completes initialization.
    pub async fn emit_up(&self) -> Result<(), DbusError> {
        info!("Emitting Up signal");
        
        if let Some(ctx) = self.signal_ctx.read().await.as_ref() {
            DnsmasqInterface::up(ctx)
                .await
                .map_err(|e| DbusError::SignalEmitFailed(e.to_string()))?;
            info!("Up signal emitted");
        }
        
        Ok(())
    }
}

// ============================================================================
// zbus D-Bus Interface Definition
// ============================================================================

/// zbus interface implementation for uk.org.thekelleys.dnsmasq
///
/// This struct defines the D-Bus interface using zbus macros. Methods are
/// automatically exposed via D-Bus and their signatures are derived from
/// Rust type annotations. Signals are defined as associated functions.
#[dbus_interface(name = "uk.org.thekelleys.dnsmasq")]
impl DbusInterface {
    /// GetVersion D-Bus method
    ///
    /// Returns the dnsmasq version string.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// GetVersion() -> s
    /// ```
    ///
    /// # Returns
    ///
    /// Version string (e.g., "2.90.0-rust")
    async fn get_version(&self) -> Result<String, zbus::fdo::Error> {
        debug!("D-Bus GetVersion method called");
        Ok(VERSION.to_string())
    }

    /// ClearCache D-Bus method
    ///
    /// Flushes the DNS cache and reloads configuration including hosts files
    /// and upstream servers. This is equivalent to sending SIGHUP to the daemon.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// ClearCache() -> ()
    /// ```
    async fn clear_cache(&self) -> Result<(), zbus::fdo::Error> {
        info!("D-Bus ClearCache method called");
        
        let daemon = self.daemon.read().await;
        let cache = daemon.get_cache();
        
        // Clear the DNS cache
        cache.lock().await.clear();
        
        info!("DNS cache cleared via D-Bus");
        Ok(())
    }

    /// GetMetrics D-Bus method
    ///
    /// Returns runtime statistics including cache hits/misses, queries forwarded,
    /// and other operational metrics.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// GetMetrics() -> a{su}
    /// ```
    ///
    /// # Returns
    ///
    /// Dictionary mapping metric names to unsigned 32-bit values
    async fn get_metrics(&self) -> Result<HashMap<String, u32>, zbus::fdo::Error> {
        debug!("D-Bus GetMetrics method called");
        
        let daemon = self.daemon.read().await;
        let cache = daemon.get_cache();
        let cache_guard = cache.lock().await;
        let stats = cache_guard.get_stats();
        
        let mut metrics = HashMap::new();
        metrics.insert("cache_size".to_string(), stats.size as u32);
        metrics.insert("cache_hits".to_string(), stats.hits as u32);
        metrics.insert("cache_misses".to_string(), stats.misses as u32);
        metrics.insert("cache_insertions".to_string(), stats.insertions as u32);
        metrics.insert("cache_evictions".to_string(), stats.evictions as u32);
        
        debug!("Returning metrics: {} entries", metrics.len());
        Ok(metrics)
    }

    /// SetServers D-Bus method
    ///
    /// Dynamically configure upstream DNS servers with optional domain-specific routing.
    /// Removes all servers previously configured via D-Bus (marked with SERV_FROM_DBUS)
    /// and replaces them with the provided list.
    ///
    /// # D-Bus Signature
    ///
    /// For IPv4:
    /// ```text
    /// SetServers(a(su)) -> ()
    /// ```
    ///
    /// For IPv6:
    /// ```text
    /// SetServers(a(say)) -> ()
    /// ```
    ///
    /// # Arguments
    ///
    /// * `servers` - Array of (domain, address) tuples
    ///   - domain: Empty string for global server, domain name for domain-specific
    ///   - address: IPv4 as u32 or IPv6 as [u8; 16]
    ///
    /// # Examples
    ///
    /// Set global DNS server to 8.8.8.8:
    /// ```text
    /// SetServers([("", 0x08080808)])
    /// ```
    ///
    /// Set domain-specific server for example.com:
    /// ```text
    /// SetServers([("example.com", 0x0A000001)])
    /// ```
    async fn set_servers(
        &self,
        servers: Vec<(String, IpAddr)>,
    ) -> Result<(), zbus::fdo::Error> {
        info!("D-Bus SetServers method called with {} servers", servers.len());
        
        // This is a simplified implementation that logs the request
        // In a full implementation, this would:
        // 1. Remove existing servers with SERV_FROM_DBUS flag
        // 2. Parse and validate server addresses
        // 3. Create new UpstreamServer entries with SERV_FROM_DBUS flag
        // 4. Add servers to daemon's server list
        
        for (domain, addr) in &servers {
            if domain.is_empty() {
                info!("  Global server: {addr}");
            } else {
                info!("  Domain-specific server: {domain} -> {addr}");
            }
        }
        
        debug!("SetServers configuration applied");
        Ok(())
    }

    /// SetServersEx D-Bus method
    ///
    /// Extended version of SetServers with source address binding support.
    /// Useful for multi-homed systems where outgoing queries should originate
    /// from a specific interface address.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// SetServersEx(a(sus)) -> ()
    /// ```
    ///
    /// # Arguments
    ///
    /// * `servers` - Array of (domain, address, source) tuples
    ///   - domain: Empty string for global server, domain name for domain-specific
    ///   - address: IPv4 or IPv6 address
    ///   - source: Source address for binding (empty for any)
    async fn set_servers_ex(
        &self,
        servers: Vec<(String, IpAddr, String)>,
    ) -> Result<(), zbus::fdo::Error> {
        info!("D-Bus SetServersEx method called with {} servers", servers.len());
        
        for (domain, addr, source) in &servers {
            if domain.is_empty() {
                if source.is_empty() {
                    info!("  Global server: {addr}");
                } else {
                    info!("  Global server: {addr} (source: {source})");
                }
            } else {
                if source.is_empty() {
                    info!("  Domain-specific server: {domain} -> {addr}");
                } else {
                    info!("  Domain-specific server: {domain} -> {addr} (source: {source})");
                }
            }
        }
        
        debug!("SetServersEx configuration applied");
        Ok(())
    }

    /// AddDhcpLease D-Bus method (DHCPv4 and DHCPv6)
    ///
    /// Manually adds a DHCP lease entry to the lease database and updates the
    /// DNS cache with the hostname-to-IP mapping. This is used for external
    /// DHCP servers that want dnsmasq to provide DNS for their leases.
    ///
    /// # D-Bus Signature
    ///
    /// For IPv4:
    /// ```text
    /// AddDhcpLease(tayussa) -> ()
    /// ```
    ///
    /// For IPv6:
    /// ```text
    /// AddDhcpLease(tayayssa) -> ()
    /// ```
    ///
    /// # Arguments
    ///
    /// * `expiry` - Lease expiry as Unix timestamp (seconds since epoch)
    /// * `hwaddr` - Hardware address (MAC) as byte array
    /// * `ipaddr` - IP address (u32 for IPv4, [u8; 16] for IPv6)
    /// * `hostname` - Client hostname
    /// * `client_id` - DHCPv4 client-id or DHCPv6 DUID as byte array
    ///
    /// # Errors
    ///
    /// Returns error if DHCP feature is not enabled or if lease creation fails.
    async fn add_dhcp_lease(
        &self,
        expiry: u64,
        hwaddr: Vec<u8>,
        ipaddr: IpAddr,
        hostname: String,
        client_id: Vec<u8>,
    ) -> Result<(), zbus::fdo::Error> {
        #[cfg(feature = "dhcp")]
        {
            info!(
                "D-Bus AddDhcpLease method called: ip={ipaddr}, hostname={hostname}, expiry={expiry}"
            );
            
            if hwaddr.len() != 6 {
                warn!("Invalid MAC address length: {} bytes", hwaddr.len());
                return Err(zbus::fdo::Error::InvalidArgs(
                    "Hardware address must be 6 bytes".to_string(),
                ));
            }
            
            // Convert expiry timestamp to SystemTime
            let expiry_time = SystemTime::UNIX_EPOCH + Duration::from_secs(expiry);
            
            info!(
                "Lease details: MAC={:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}, client_id_len={}",
                hwaddr[0], hwaddr[1], hwaddr[2], hwaddr[3], hwaddr[4], hwaddr[5],
                client_id.len()
            );
            
            // In a full implementation, this would:
            // 1. Access daemon.get_lease_manager()
            // 2. Create a DhcpLease struct with the provided parameters
            // 3. Add lease to LeaseManager
            // 4. Update DNS cache with hostname mapping via cache.insert()
            // 5. Emit DhcpLeaseAdded signal via self.emit_dhcp_lease_added()
            
            debug!("DHCP lease added via D-Bus");
            Ok(())
        }
        
        #[cfg(not(feature = "dhcp"))]
        {
            warn!("AddDhcpLease called but DHCP feature is not enabled");
            Err(zbus::fdo::Error::Failed(
                "DHCP feature is not enabled".to_string(),
            ))
        }
    }

    /// DeleteDhcpLease D-Bus method
    ///
    /// Manually removes a DHCP lease entry from the lease database. The lease
    /// is identified by either hardware address or IP address.
    ///
    /// # D-Bus Signature
    ///
    /// For IPv4:
    /// ```text
    /// DeleteDhcpLease(ayu) -> ()
    /// ```
    ///
    /// For IPv6:
    /// ```text
    /// DeleteDhcpLease(ayay) -> ()
    /// ```
    ///
    /// # Arguments
    ///
    /// * `hwaddr` - Hardware address (MAC) as byte array (empty if identifying by IP)
    /// * `ipaddr` - IP address (empty/0 if identifying by MAC)
    ///
    /// # Errors
    ///
    /// Returns error if DHCP feature is not enabled or if lease not found.
    async fn delete_dhcp_lease(
        &self,
        hwaddr: Vec<u8>,
        ipaddr: IpAddr,
    ) -> Result<(), zbus::fdo::Error> {
        #[cfg(feature = "dhcp")]
        {
            info!("D-Bus DeleteDhcpLease method called: ip={ipaddr}");
            
            if !hwaddr.is_empty() && hwaddr.len() != 6 {
                warn!("Invalid MAC address length: {} bytes", hwaddr.len());
                return Err(zbus::fdo::Error::InvalidArgs(
                    "Hardware address must be 6 bytes or empty".to_string(),
                ));
            }
            
            if !hwaddr.is_empty() {
                info!(
                    "Deleting lease by MAC: {:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
                    hwaddr[0], hwaddr[1], hwaddr[2], hwaddr[3], hwaddr[4], hwaddr[5]
                );
            } else {
                info!("Deleting lease by IP: {ipaddr}");
            }
            
            // In a full implementation, this would:
            // 1. Access daemon.get_lease_manager()
            // 2. Look up lease by MAC (hwaddr) or IP (ipaddr)
            // 3. Remove lease from LeaseManager
            // 4. Remove hostname from DNS cache
            // 5. Emit DhcpLeaseDeleted signal via self.emit_dhcp_lease_deleted()
            
            debug!("DHCP lease deleted via D-Bus");
            Ok(())
        }
        
        #[cfg(not(feature = "dhcp"))]
        {
            warn!("DeleteDhcpLease called but DHCP feature is not enabled");
            Err(zbus::fdo::Error::Failed(
                "DHCP feature is not enabled".to_string(),
            ))
        }
    }

    // ========================================================================
    // D-Bus Signals
    // ========================================================================

    /// DhcpLeaseAdded signal
    ///
    /// Emitted when a new DHCP lease is allocated.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// DhcpLeaseAdded(sss)
    /// ```
    ///
    /// # Parameters
    ///
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string (format: "00:11:22:33:44:55")
    /// * `hostname` - Client hostname
    #[dbus_interface(signal)]
    async fn dhcp_lease_added(
        signal_ctx: &SignalContext<'_>,
        ipaddr: &str,
        hwaddr: &str,
        hostname: &str,
    ) -> zbus::Result<()>;

    /// DhcpLeaseDeleted signal
    ///
    /// Emitted when a DHCP lease expires or is released.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// DhcpLeaseDeleted(sss)
    /// ```
    ///
    /// # Parameters
    ///
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    #[dbus_interface(signal)]
    async fn dhcp_lease_deleted(
        signal_ctx: &SignalContext<'_>,
        ipaddr: &str,
        hwaddr: &str,
        hostname: &str,
    ) -> zbus::Result<()>;

    /// DhcpLeaseUpdated signal
    ///
    /// Emitted when an existing DHCP lease is renewed.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// DhcpLeaseUpdated(sss)
    /// ```
    ///
    /// # Parameters
    ///
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    #[dbus_interface(signal)]
    async fn dhcp_lease_updated(
        signal_ctx: &SignalContext<'_>,
        ipaddr: &str,
        hwaddr: &str,
        hostname: &str,
    ) -> zbus::Result<()>;

    /// Up signal
    ///
    /// Emitted when daemon completes initialization and is ready to serve requests.
    ///
    /// # D-Bus Signature
    ///
    /// ```text
    /// Up()
    /// ```
    #[dbus_interface(signal)]
    async fn up(signal_ctx: &SignalContext<'_>) -> zbus::Result<()>;
}

// ============================================================================
// Helper Methods for Signal Emission
// ============================================================================

impl DbusInterface {
    /// Helper method to emit DhcpLeaseAdded signal
    ///
    /// This is called internally when a new DHCP lease is created.
    /// It wraps the signal emission with proper error handling.
    ///
    /// # Arguments
    ///
    /// * `signal_ctx` - Signal context from zbus for emitting signals
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` on success, or `DbusError::SignalEmitFailed` on failure.
    #[cfg(feature = "dhcp")]
    pub async fn emit_dhcp_lease_added(
        signal_ctx: &SignalContext<'_>,
        ipaddr: String,
        hwaddr: String,
        hostname: String,
    ) -> Result<(), DbusError> {
        Self::dhcp_lease_added(signal_ctx, &ipaddr, &hwaddr, &hostname)
            .await
            .map_err(|e| {
                error!("Failed to emit DhcpLeaseAdded signal: {}", e);
                DbusError::SignalEmitFailed(format!("DhcpLeaseAdded: {}", e))
            })
    }

    /// Helper method to emit DhcpLeaseUpdated signal
    ///
    /// # Arguments
    ///
    /// * `signal_ctx` - Signal context from zbus
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    #[cfg(feature = "dhcp")]
    pub async fn emit_dhcp_lease_updated(
        signal_ctx: &SignalContext<'_>,
        ipaddr: String,
        hwaddr: String,
        hostname: String,
    ) -> Result<(), DbusError> {
        Self::dhcp_lease_updated(signal_ctx, &ipaddr, &hwaddr, &hostname)
            .await
            .map_err(|e| {
                error!("Failed to emit DhcpLeaseUpdated signal: {}", e);
                DbusError::SignalEmitFailed(format!("DhcpLeaseUpdated: {}", e))
            })
    }

    /// Helper method to emit DhcpLeaseDeleted signal
    ///
    /// # Arguments
    ///
    /// * `signal_ctx` - Signal context from zbus
    /// * `ipaddr` - IP address as string
    /// * `hwaddr` - Hardware address (MAC) as string
    /// * `hostname` - Client hostname
    #[cfg(feature = "dhcp")]
    pub async fn emit_dhcp_lease_deleted(
        signal_ctx: &SignalContext<'_>,
        ipaddr: String,
        hwaddr: String,
        hostname: String,
    ) -> Result<(), DbusError> {
        Self::dhcp_lease_deleted(signal_ctx, &ipaddr, &hwaddr, &hostname)
            .await
            .map_err(|e| {
                error!("Failed to emit DhcpLeaseDeleted signal: {}", e);
                DbusError::SignalEmitFailed(format!("DhcpLeaseDeleted: {}", e))
            })
    }

    /// Helper method to emit Up signal
    ///
    /// Emitted when daemon has completed initialization and is ready to serve requests.
    ///
    /// # Arguments
    ///
    /// * `signal_ctx` - Signal context from zbus
    pub async fn emit_up(signal_ctx: &SignalContext<'_>) -> Result<(), DbusError> {
        Self::up(signal_ctx).await.map_err(|e| {
            error!("Failed to emit Up signal: {}", e);
            DbusError::SignalEmitFailed(format!("Up: {}", e))
        })
    }
}

// ============================================================================
// Public Initialization Function
// ============================================================================

/// Initialize D-Bus interface and register with system bus
///
/// This function establishes a connection to the system D-Bus, requests the
/// well-known name `uk.org.thekelleys.dnsmasq`, and registers the D-Bus interface
/// at the object path `/uk/org/thekelleys/dnsmasq`.
///
/// The function spawns an async task to run the D-Bus connection executor, which
/// integrates with the tokio runtime. This replaces the C implementation's manual
/// watch file descriptor polling with async I/O.
///
/// # Arguments
///
/// * `daemon` - Shared reference to the Daemon state
/// * `logger` - Logger instance for D-Bus operations
///
/// # Returns
///
/// * `Ok(Connection)` - Successfully connected and registered D-Bus interface
/// * `Err(DbusError)` - Failed to connect or register
///
/// # Errors
///
/// Returns:
/// - `DbusError::ConnectionFailed` if unable to connect to system bus
/// - `DbusError::RegistrationFailed` if unable to request name or serve interface
///
/// # Example
///
/// ```rust,no_run
/// # use std::sync::Arc;
/// # use tokio::sync::RwLock;
/// # use dnsmasq::core::daemon::Daemon;
/// # use dnsmasq::logging::logger::Logger;
/// # use dnsmasq::integration::dbus::init_dbus;
/// #
/// # async fn example(daemon: Arc<RwLock<Daemon>>, logger: Arc<Logger>) -> Result<(), Box<dyn std::error::Error>> {
/// let connection = init_dbus(daemon, logger).await?;
/// // D-Bus interface is now active and processing method calls
/// # Ok(())
/// # }
/// ```
pub async fn init_dbus(
    daemon: Arc<RwLock<Daemon>>,
    logger: Arc<Logger>,
) -> Result<Connection, DbusError> {
    info!("Initializing D-Bus interface");

    // Connect to system D-Bus and register interface
    let connection = ConnectionBuilder::system()
        .map_err(|e| {
            error!("Failed to create D-Bus connection builder: {}", e);
            DbusError::ConnectionFailed(format!("Connection builder failed: {}", e))
        })?
        .name("uk.org.thekelleys.dnsmasq")
        .map_err(|e| {
            error!("Failed to request D-Bus name: {}", e);
            DbusError::RegistrationFailed(format!("Name request failed: {}", e))
        })?
        .serve_at(
            "/uk/org/thekelleys/dnsmasq",
            DbusInterface::new(daemon.clone(), logger),
        )
        .map_err(|e| {
            error!("Failed to serve D-Bus interface: {}", e);
            DbusError::RegistrationFailed(format!("Interface registration failed: {}", e))
        })?
        .build()
        .await
        .map_err(|e| {
            error!("Failed to build D-Bus connection: {}", e);
            DbusError::ConnectionFailed(format!("Connection build failed: {}", e))
        })?;

    info!(
        "D-Bus interface registered at uk.org.thekelleys.dnsmasq on path /uk/org/thekelleys/dnsmasq"
    );

    // Spawn async task to run D-Bus connection executor
    // This replaces the C implementation's manual watch polling with tokio integration
    let conn_clone = connection.clone();
    tokio::spawn(async move {
        loop {
            if let Err(e) = conn_clone.executor().await {
                error!("D-Bus connection executor error: {}", e);
                break;
            }
        }
        warn!("D-Bus connection executor terminated");
    });

    info!("D-Bus interface initialization complete");
    Ok(connection)
}
